# Generated by Django 4.1.6 on 2023-02-26 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_rename_description_recipe_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Время должно быть не меньше минуты')], verbose_name='время приготовления'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='colour',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Не допустимый символ HEX(цвета)', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')], verbose_name='цвет'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Только буквы, цифры и @/./+/-/_', regex='^[\\w.@+-]+\\Z')], verbose_name='название тега'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='unique_ingredient'),
        ),
        migrations.AddConstraint(
            model_name='ingredientquantity',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_ingredient_quantity'),
        ),
    ]
