# Generated by Django 4.1.6 on 2023-03-02 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_rename_quantity_ingredientquantity_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='colour',
            new_name='color',
        ),
    ]
